repos: 
  - repo: https://github.com/ambv/black 
    rev: stable
    hooks: 
      - id: black 
        exclude: doc/|monitoring/|scripts/|tool/|test/ 
  - repo: https://github.com/pre-commit/pre-commit-hooks 
    rev: v1.2.3 
    hooks: 
      - id: flake8 
        exclude: doc/|monitoring/|scripts/|tool/|test/
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (pyi)
        types: [pyi]
